### ISSUE TITLE
Compilation difficulty - VS 2022

### ISSUE THREAD

**Issue by crohr88** [sssomeone/SurfaceVoronoi#3]
Hello, 

I am trying to compile your code on Visual Studio 2022 (including the Model3D and Geodesic libraries, which don't work with my version of VS). My goal is to create some Matlab bindings for this very interesting work. 

I have an error in RichModel.cpp that I can't resolve. I tried to with the commented code but it results in the GVD_RVD example crashing - after running it crashes here in GVD_RVD.hpp:

```c++
threeNeighboringFaces[0] = model.Edge(model.Edge(firstEdge).indexOfReverseEdge).indexOfFrontFace;
threeNeighboringFaces[1] = model.Edge(model.Edge(firstEdge).indexOfLeftEdge).indexOfFrontFace;
threeNeighboringFaces[2] = model.Edge(model.Edge(firstEdge).indexOfRightEdge).indexOfFrontFace;
```
Do you have any idea what might be going on? I don't have the expertise in C++ to properly understand what is happening. 

Thank you!

![image](https://github.com/user-attachments/assets/2a4decc1-524c-4f6e-9a0f-886efaeb2a96)

Visual Studio 2022 17.11.2
boost 1.86
eigen 3.4.0
CGAL 5.6.1

**Comment by crohr88** [comment]
It appears this issue can be fixed by replacing line 100 of RichModel.cpp as follows:
```cpp
//m_Edges.swap(vector<CEdge>(m_Edges));
m_Edges.shrink_to_fit();
```

There is still the issue highlighted by another user with the EDGVD example not computing as per the paper though, described in [Issue 2](https://github.com/sssomeone/SurfaceVoronoi/issues/2).

**Comment by sssomeone** [comment]
I'm very sorry to see your message so late. For the message you mentioned, you only need to delete the corresponding line of code, which will not affect the results. Next I will implement a robust version of the algorithm in this article. Sorry to see you so late

**Comment by crohr88** [comment]
> I'm very sorry to see your message so late. For the message you mentioned, you only need to delete the corresponding line of code, which will not affect the results. Next I will implement a robust version of the algorithm in this article. Sorry to see you so late

No problem at all. I have since successfully used your very good algorithm on a range of challenging geometries. 
Currently I am working on how it can be extended to work for my application, which sometimes requires a segmentation to cross over disconnected manifolds (seeds on one manifold influencing the diagram of another manifold). This is relevant to data acquisition and interpolation where the data is sampled on a non-connected piece of geometry but interpolation is desired to be conducted smoothly across them.
